name: ci-cd

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - run: npm test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verificar Dockerfile
        run: test -f Dockerfile

      - name: Simular construcción de imagen
        run: echo "Imagen app:${{ github.sha }} construida correctamente"

      - name: Simular despliegue
        run: echo "Despliegue ejecutado correctamente"